// swift-tools-version:5.9
// Auto-generated by CI – do not edit manually.
// XsollaOfferwallSDK v0.3.0
import PackageDescription

let package = Package(
    name: "XsollaOfferwallSDK",
    platforms: [
        .iOS(.v12)
    ],
    products: [
        .library(
            name: "XsollaOfferwallSDK",
            targets: ["XsollaOfferwallSDK"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "XsollaOfferwallSDK",
            url: "https://cdn.xsolla.net/offerwallsdk-bucket-prod/release/0.3.0/XsollaOfferwallSDK.xcframework.zip",
            checksum: "3441588a9864e84704c6f280c9537c30ec9161a2e7f066e903e5903f79411f9a"
        ),
    ]
)
