// swift-tools-version:5.9
// Auto-generated by CI – do not edit manually.
// XsollaOfferwallSDK v0.2.0
import PackageDescription

let package = Package(
    name: "XsollaOfferwallSDK",
    platforms: [
        .iOS(.v12)
    ],
    products: [
        .library(
            name: "XsollaOfferwallSDK",
            targets: ["XsollaOfferwallSDK"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "XsollaOfferwallSDK",
            url: "https://github.com/xsolla/xsolla-offerwall-ios-swift-package/releases/download/0.2.0/XsollaOfferwallSDK.xcframework.zip",
            checksum: "4a6a09f64e889326dddff49ea6cb0d9153a53ffcf89868e4090ee67887bf7dca"
        ),
    ]
)
