// swift-tools-version:5.9
// Auto-generated by CI – do not edit manually.
// XsollaOfferwallSDK v0.3.0
import PackageDescription

let package = Package(
    name: "XsollaOfferwallSDK",
    platforms: [
        .iOS(.v12)
    ],
    products: [
        .library(
            name: "XsollaOfferwallSDK",
            targets: ["XsollaOfferwallSDK"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "XsollaOfferwallSDK",
            url: "https://cdn.xsolla.net/offerwallsdk-bucket-prod/release/0.3.0/XsollaOfferwallSDK.xcframework.zip",
            checksum: "2c0a46c06c2e8d065dbbf1e16797ffe24fd54f5d92a6787eb972c8479f530b31"
        ),
    ]
)
